[package]
name = "rocket-surrealdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.217"
surrealdb = "2.1.4"
thiserror = "2.0.11"
