services:
  rocket:
    build: .
    ports:
      - 8000:8000
  surrealdb:
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - user0
      - --pass
      - password0
    image: surrealdb/surrealdb:latest
    ports:
      - 8001:8001
